language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
  - python setup.py install
before_script:
  -project # did it get installed ?
script:
  - py.test